[project]
name = "sih-2025"
version = "0.1.0"
description = "smart traffic management system for urban congestion"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.3",
    "opencv-python>=4.11.0.86",
]
